data_dir: /home/mikasaackerman/umass-amherst/courses/semester-2/cs670/UMass-CS670-Project/source-data
device: cpu
output_dir: /home/mikasaackerman/umass-amherst/courses/semester-2/cs670/UMass-CS670-Project/output
root_dir: /home/mikasaackerman/umass-amherst/courses/semester-2/cs670/UMass-CS670-Project
use_gpu: false
